---
apiVersion: v1
kind: Service
metadata:
  name: cache-service
spec:
  selector: 
    app: cache
  type: ClusterIP
  ports:
    - name: dpport
      targetPort: 6379
      protocol: TCP
      port: 6379