---
apiVersion: v1
kind: Service
metadata:
  name: saleor-service
spec:
  selector: 
    app: saleor
  type: LoadBalancer
  ports:
    - name: dpport
      targetPort: 8000
      protocol: TCP
      port: 8000