apiVersion: apps/v1
kind: Deployment
metadata:
  name: saleor-deployment
  labels: 
    app: saleor
spec:
  minReadySeconds: 10
  replicas: 1
  selector:
    matchLabels:
      app: saleor
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25
      maxUnavailable: 25
  template:
    metadata: 
      name: saleor-pod
      labels:
        app: saleor
  spec: 
    containers:
      - image: shaikkhajaibrahim/saleor:DEV
        name: saleor-container
        ports:
          - containerPort: 8000
            protocol: TCP          
        command:
          - python
          - manage.py
          - runserver
          - 0.0.0.0:8000    